# Generated by Django 4.0.6 on 2022-08-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('he', 'Hebrew'), ('en', 'English')], default='en-us', max_length=10),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
